name: placewaifu
version: 0.1.0.0
github: "Xetera/placewaifu"
license: MIT
author: "Xetera"
copyright: "2019 Xetera"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README

dependencies:
  - base
  - base64-bytestring
  - bytestring
  - directory
  - filepath
  - JuicyPixels
  - mtl
  - random
  - servant
  - servant-server
  - text
  - time
  - transformers
  - wai
  - warp

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - ViewPatterns

library:
  source-dirs: src

executables:
  placewaifu:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - placewaifu

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - hspec
      - placewaifu
      - QuickCheck

benchmarks:
  bench:
    main: Benchmark.hs
    source-dirs: benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - criterion
      - placewaifu
