name: placewaifu
version: 0.1.0.0
github: "Xetera/placewaifu"
license: MIT
author: "Xetera"
copyright: "2019 Xetera"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README

dependencies:
  - aeson
  - base
  - base64-bytestring
  - bytestring
  - containers
  - filepath
  - http-types
  - JuicyPixels
  - mtl
  - random
  - servant
  - servant-server
  - text
  - time
  - transformers
  - unordered-containers
  - wai
  - warp
  - yaml
  - monad-logger

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DerivingStrategies
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - ViewPatterns

library:
  source-dirs: src

executables:
  placewaifu:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - optparse-applicative
      - placewaifu
