name: placewaifu
version: 0.1.0.0
github: "Xetera/placewaifu"
license: BSD3
author: "Xetera"
copyright: "2019 Xetera"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README

dependencies:
  - base
  - bytestring
  - directory
  - filepath
  - hip
  - mtl
  - random
  - servant
  - servant-server
  - text
  - time
  - transformers
  - wai
  - warp

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - ViewPatterns

executable:
  main: Main.hs
  source-dirs: src
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
