---
- hosts: all
  vars:
    app: placewaifu
  roles:
    - role: dokku_bot.ansible_dokku
  tasks:
    - name: Setting domains
      dokku_domains:
        app: "{{ app }}"
        domains:
          - placewaifu.com
    - name: Setting ports
      dokku_ports:
        app: "{{ app }}"
        mappings:
          - http:80:1234
