---
name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Store package.json version
        run: |
          echo "placewaifu_version=$(jq -r '.version' web/package.json)" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/xetera/placewaifu:${{ env.placewaifu_version }}
            ghcr.io/xetera/placewaifu:latest
